name: CI
run-name: CI triggered by push from ${{ github.actor }}
on: [push]
jobs:
  Build-On-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
        
      - run: cat /etc/alpine-release
        shell: alpine.sh {0}
