name: CI
run-name: CI triggered by push from ${{ github.actor }}
on: [push]
jobs:
  Build-On-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip install mypy pylint detect-secrets
      - uses: pre-commit/action@v3.0.0
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: docker build --ssh default --target tox -t multikeyjwt:tox .
      - name: Echo SSH_AUTH_SOCK
        run: echo $SSH_AUTH_SOCK
      - run: docker run --rm -v ${{ github.workspace }}:/app -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK -e SSH_AUTH_SOCK multikeyjwt:tox
