name: CI
run-name: CI triggered by push from ${{ github.actor }}
on: [push]
jobs:
  Build-On-Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
        
      - run: cat /etc/alpine-release
        shell: alpine.sh {0}

#  Build-On-Debian:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: jtdor/build-deb-action@v1
#        env:
#          DEB_BUILD_OPTIONS: noautodbgsym
#        with:
#          buildpackage-opts: --build=binary --no-sign

  Build-On-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: docker exec -i multikeyjwt_devel /bin/bash -c "pre-commit install"
      - run: docker exec -i multikeyjwt_devel /bin/bash -c "pre-commit run --all-files"
      - run: docker build --ssh default --target tox -t multikeyjwt:tox .
      - run: docker run --rm -it -v `pwd`":/app" `echo $DOCKER_SSHAGENT` multikeyjwt:tox
      #- name: Docker build
      #  run: |
      #    export DOCKER_BUILDKIT=1
      #    export DOCKER_SSHAGENT="-v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock"
      #    docker build --ssh default --target devel_shell -t multikeyjwt:devel_shell .
